// Road-sign flashcards — merged from two RSA sources:
//   * "Irish Road Traffic Signs" (full categorised set, caption per sign)
//   * "Driving Test Road Signs 2024" (official numbered answer sheet)
// Duplicates and non-essential destination / detour boards removed.
// Images live in  public/signs/  and are served as  /signs/<file>.png

export const ROAD_SIGN_CATEGORIES = [
  { id: "regulatory", label: "Regulatory Signs", swatch: "bg-red-600" },
  { id: "warning",    label: "Warning Signs",    swatch: "bg-amber-500", dark: true },
  { id: "roadworks",  label: "Roadworks Signs",  swatch: "bg-orange-600" },
  { id: "markings",   label: "Road Markings",    swatch: "bg-slate-600" },
  { id: "info",       label: "Motorway & Info",  swatch: "bg-blue-600" },
];

export const ROAD_SIGN_CAT = Object.fromEntries(ROAD_SIGN_CATEGORIES.map(c => [c.id, c]));

const RAW = [
  { id: 1, img: "/signs/001.png", name: "Bus only street", c: "regulatory" },
  { id: 2, img: "/signs/002.png", name: "Clearway", c: "regulatory" },
  { id: 3, img: "/signs/003.png", name: "Disc parking plate", c: "regulatory" },
  { id: 4, img: "/signs/004.png", name: "End of the restriction zone", c: "regulatory" },
  { id: 5, img: "/signs/005.png", name: "Height restriction", c: "regulatory" },
  { id: 6, img: "/signs/006.png", name: "Keep left", c: "regulatory" },
  { id: 7, img: "/signs/007.png", name: "Keep right", c: "regulatory" },
  { id: 8, img: "/signs/008.png", name: "Keep Straight Ahead", c: "regulatory" },
  { id: 9, img: "/signs/009.png", name: "Lane closed", c: "regulatory" },
  { id: 10, img: "/signs/010.png", name: "Lane open", c: "regulatory" },
  { id: 11, img: "/signs/011.png", name: "Left turn ahead", c: "regulatory" },
  { id: 12, img: "/signs/012.png", name: "Max Gross Weight (7.5T)", c: "regulatory" },
  { id: 13, img: "/signs/013.png", name: "Max Vehicle Length (10.5m)", c: "regulatory" },
  { id: 14, img: "/signs/014.png", name: "Max Vehicle Width (2.5m)", c: "regulatory" },
  { id: 15, img: "/signs/015.png", name: "Maximum Axle Weight 4T", c: "regulatory" },
  { id: 16, img: "/signs/016.png", name: "Maximum Speed Limit", c: "regulatory" },
  { id: 17, img: "/signs/017.png", name: "Move into the left-hand lane", c: "regulatory" },
  { id: 18, img: "/signs/018.png", name: "Move into the right-hand lane", c: "regulatory" },
  { id: 19, img: "/signs/019.png", name: "No Bicycles", c: "regulatory" },
  { id: 20, img: "/signs/020.png", name: "No entry", c: "regulatory" },
  { id: 21, img: "/signs/021.png", name: "No entry for large vehicles", c: "regulatory" },
  { id: 22, img: "/signs/022.png", name: "No entry for pedestrians", c: "regulatory" },
  { id: 23, img: "/signs/023.png", name: "No entry to goods vehicles", c: "regulatory" },
  { id: 24, img: "/signs/024.png", name: "No left turn", c: "regulatory" },
  { id: 25, img: "/signs/025.png", name: "No overtaking", c: "regulatory" },
  { id: 26, img: "/signs/026.png", name: "No Overtaking For 3-Axle Vehicles", c: "regulatory" },
  { id: 27, img: "/signs/027.png", name: "No parking", c: "regulatory" },
  { id: 28, img: "/signs/028.png", name: "No parking of large vehicles", c: "regulatory" },
  { id: 29, img: "/signs/029.png", name: "No Parking Permitted", c: "regulatory" },
  { id: 30, img: "/signs/030.png", name: "No Ridden Or Accompanied Horses", c: "regulatory" },
  { id: 31, img: "/signs/031.png", name: "No right turn", c: "regulatory" },
  { id: 32, img: "/signs/032.png", name: "No stopping", c: "regulatory" },
  { id: 33, img: "/signs/033.png", name: "No Straight Ahead", c: "regulatory" },
  { id: 34, img: "/signs/034.png", name: "No U-turn", c: "regulatory" },
  { id: 35, img: "/signs/035.png", name: "No vehicles", c: "regulatory" },
  { id: 36, img: "/signs/036.png", name: "Parking permitted", c: "regulatory" },
  { id: 37, img: "/signs/037.png", name: "Pass either side", c: "regulatory" },
  { id: 38, img: "/signs/038.png", name: "Pedestrianised Street", c: "regulatory" },
  { id: 39, img: "/signs/039.png", name: "Pedestrians & Bicycles Only", c: "regulatory" },
  { id: 40, img: "/signs/040.png", name: "Periodic speed limit sign", c: "regulatory" },
  { id: 41, img: "/signs/041.png", name: "Periodic speed limit sign at school", c: "regulatory" },
  { id: 42, img: "/signs/042.png", name: "Right turn ahead", c: "regulatory" },
  { id: 43, img: "/signs/043.png", name: "School warden's stop sign", c: "regulatory" },
  { id: 44, img: "/signs/044.png", name: "Separate Bicycle & Pedestrian Lanes", c: "regulatory" },
  { id: 45, img: "/signs/045.png", name: "Stop", c: "regulatory" },
  { id: 46, img: "/signs/046.png", name: "Straight ahead", c: "regulatory" },
  { id: 47, img: "/signs/047.png", name: "Street for pedestrians", c: "regulatory" },
  { id: 48, img: "/signs/048.png", name: "Taxi rank", c: "regulatory" },
  { id: 49, img: "/signs/049.png", name: "Tram and access only street", c: "regulatory" },
  { id: 50, img: "/signs/050.png", name: "Tram only street", c: "regulatory" },
  { id: 51, img: "/signs/051.png", name: "Turn left", c: "regulatory" },
  { id: 52, img: "/signs/052.png", name: "Turn right", c: "regulatory" },
  { id: 53, img: "/signs/053.png", name: "Variable speed limit", c: "regulatory" },
  { id: 54, img: "/signs/054.png", name: "Yield", c: "regulatory" },
  { id: 55, img: "/signs/055.png", name: "Accompanied horses and ponies", c: "warning" },
  { id: 56, img: "/signs/056.png", name: "Automatic level crossing ahead", c: "warning" },
  { id: 57, img: "/signs/057.png", name: "Beware Of Cattle", c: "warning" },
  { id: 58, img: "/signs/058.png", name: "Beware Of Deer Or Wild Animals", c: "warning" },
  { id: 59, img: "/signs/059.png", name: "Beware Of Sheep", c: "warning" },
  { id: 60, img: "/signs/060.png", name: "Cattle and farm animals", c: "warning" },
  { id: 61, img: "/signs/061.png", name: "Chevron board", c: "warning" },
  { id: 62, img: "/signs/062.png", name: "Children crossing", c: "warning" },
  { id: 63, img: "/signs/063.png", name: "Crossroad", c: "warning" },
  { id: 64, img: "/signs/064.png", name: "Crossroads", c: "warning" },
  { id: 65, img: "/signs/065.png", name: "Crossroads Ahead With Road Of Higher Importance", c: "warning" },
  { id: 66, img: "/signs/066.png", name: "Crossroads Ahead With Road Of Less Importance", c: "warning" },
  { id: 67, img: "/signs/067.png", name: "Crossroads with dual carriageway", c: "warning" },
  { id: 68, img: "/signs/068.png", name: "Crosswinds", c: "warning" },
  { id: 69, img: "/signs/069.png", name: "Danger of falling rocks", c: "warning" },
  { id: 70, img: "/signs/070.png", name: "Dangerous bend ahead", c: "warning" },
  { id: 71, img: "/signs/071.png", name: "Dangerous corner ahead", c: "warning" },
  { id: 72, img: "/signs/072.png", name: "Dangerous Left Bend Ahead", c: "warning" },
  { id: 73, img: "/signs/073.png", name: "Dangerous Left Corner Ahead", c: "warning" },
  { id: 74, img: "/signs/074.png", name: "Deer or wild animals", c: "warning" },
  { id: 75, img: "/signs/075.png", name: "Drive on left", c: "warning" },
  { id: 76, img: "/signs/076.png", name: "Dual carriageway ends", c: "warning" },
  { id: 77, img: "/signs/077.png", name: "Guarded Level Crossing Ahead", c: "warning" },
  { id: 78, img: "/signs/078.png", name: "Lane Loss", c: "warning" },
  { id: 79, img: "/signs/079.png", name: "Level crossing ahead with lights and barriers", c: "warning" },
  { id: 80, img: "/signs/080.png", name: "Level crossing ahead, guarded by gates or lifting barrier", c: "warning" },
  { id: 81, img: "/signs/081.png", name: "Level crossing ahead, unguarded by gates or lifting barrier", c: "warning" },
  { id: 82, img: "/signs/082.png", name: "Loop Road Ahead", c: "warning" },
  { id: 83, img: "/signs/083.png", name: "Low bridge ahead (height restriction shown)", c: "warning" },
  { id: 84, img: "/signs/084.png", name: "Low flying aircraft", c: "warning" },
  { id: 85, img: "/signs/085.png", name: "Merging / diverging traffic", c: "warning" },
  { id: 86, img: "/signs/086.png", name: "Merging traffic", c: "warning" },
  { id: 87, img: "/signs/087.png", name: "Mini-roundabout ahead", c: "warning" },
  { id: 88, img: "/signs/088.png", name: "Overhead electric cables", c: "warning" },
  { id: 89, img: "/signs/089.png", name: "Pedestrian crossing ahead", c: "warning" },
  { id: 90, img: "/signs/090.png", name: "Restricted headroom", c: "warning" },
  { id: 91, img: "/signs/091.png", name: "Road divides", c: "warning" },
  { id: 92, img: "/signs/092.png", name: "Road narrows from left", c: "warning" },
  { id: 93, img: "/signs/093.png", name: "Road narrows from right", c: "warning" },
  { id: 94, img: "/signs/094.png", name: "Road narrows on both sides", c: "warning" },
  { id: 95, img: "/signs/095.png", name: "Roundabout ahead", c: "warning" },
  { id: 96, img: "/signs/096.png", name: "School ahead", c: "warning" },
  { id: 97, img: "/signs/097.png", name: "School children crossing ahead", c: "warning" },
  { id: 98, img: "/signs/098.png", name: "Series of bumps or hollows ahead", c: "warning" },
  { id: 99, img: "/signs/099.png", name: "Series of dangerous bends ahead", c: "warning" },
  { id: 100, img: "/signs/100.png", name: "Series of dangerous corners ahead", c: "warning" },
  { id: 101, img: "/signs/101.png", name: "Sharp Dip Ahead", c: "warning" },
  { id: 102, img: "/signs/102.png", name: "Sharp rise ahead", c: "warning" },
  { id: 103, img: "/signs/103.png", name: "Sheep", c: "warning" },
  { id: 104, img: "/signs/104.png", name: "Side road", c: "warning" },
  { id: 105, img: "/signs/105.png", name: "Side road of equal importance", c: "warning" },
  { id: 106, img: "/signs/106.png", name: "Side Road Of Less Importance On The Left Ahead", c: "warning" },
  { id: 107, img: "/signs/107.png", name: "Slippery for cyclists", c: "warning" },
  { id: 108, img: "/signs/108.png", name: "Slippery road ahead", c: "warning" },
  { id: 109, img: "/signs/109.png", name: "Staggered crossroads", c: "warning" },
  { id: 110, img: "/signs/110.png", name: "Start Of Climbing Lane", c: "warning" },
  { id: 111, img: "/signs/111.png", name: "Start Of Passing Lane", c: "warning" },
  { id: 112, img: "/signs/112.png", name: "Steep ascent ahead", c: "warning" },
  { id: 113, img: "/signs/113.png", name: "Steep descent ahead", c: "warning" },
  { id: 114, img: "/signs/114.png", name: "T-junction", c: "warning" },
  { id: 115, img: "/signs/115.png", name: "T-Junction Ahead With Road Of Higher Importance", c: "warning" },
  { id: 116, img: "/signs/116.png", name: "T-Junction Ahead With Road Of Less Importance To The Right", c: "warning" },
  { id: 117, img: "/signs/117.png", name: "T-junction of equal importance", c: "warning" },
  { id: 118, img: "/signs/118.png", name: "T-junction with dual carriageway", c: "warning" },
  { id: 119, img: "/signs/119.png", name: "Traffic cross-over ahead", c: "warning" },
  { id: 120, img: "/signs/120.png", name: "Traffic signals ahead", c: "warning" },
  { id: 121, img: "/signs/121.png", name: "Tram lane crossing ahead", c: "warning" },
  { id: 122, img: "/signs/122.png", name: "Tram lane warning for pedestrians \\\\\\\\\\\\\\\\u2013 Look Both Ways", c: "warning" },
  { id: 123, img: "/signs/123.png", name: "Tram lane warning for pedestrians \\\\\\\\\\\\\\\\u2013 Look Left", c: "warning" },
  { id: 124, img: "/signs/124.png", name: "Tram lane warning for pedestrians \\\\\\\\\\\\\\\\u2013 Look Right", c: "warning" },
  { id: 125, img: "/signs/125.png", name: "Tunnel ahead", c: "warning" },
  { id: 126, img: "/signs/126.png", name: "Two-way traffic", c: "warning" },
  { id: 127, img: "/signs/127.png", name: "Unprotected Body Of Water Ahead", c: "warning" },
  { id: 128, img: "/signs/128.png", name: "Y-junction", c: "warning" },
  { id: 129, img: "/signs/129.png", name: "Y-Junction Ahead With Road Of Less Importance To The Right", c: "warning" },
  { id: 130, img: "/signs/130.png", name: "Y-junction of equal importance", c: "warning" },
  { id: 131, img: "/signs/131.png", name: "End Of Roadworks", c: "roadworks" },
  { id: 132, img: "/signs/132.png", name: "Flagman ahead", c: "roadworks" },
  { id: 133, img: "/signs/133.png", name: "Go (manual traffic control)", c: "roadworks" },
  { id: 134, img: "/signs/134.png", name: "Lanes diverge at crossover", c: "roadworks" },
  { id: 135, img: "/signs/135.png", name: "Lanes Rejoin At Crossover", c: "roadworks" },
  { id: 136, img: "/signs/136.png", name: "Loose chippings", c: "roadworks" },
  { id: 137, img: "/signs/137.png", name: "Move to left", c: "roadworks" },
  { id: 138, img: "/signs/138.png", name: "Move to right", c: "roadworks" },
  { id: 139, img: "/signs/139.png", name: "Nearside Lane (Of Two) Closed", c: "roadworks" },
  { id: 140, img: "/signs/140.png", name: "Nearside lane of two closed", c: "roadworks" },
  { id: 141, img: "/signs/141.png", name: "Offside lane of three closed", c: "roadworks" },
  { id: 142, img: "/signs/142.png", name: "Offside lane of two closed", c: "roadworks" },
  { id: 143, img: "/signs/143.png", name: "One-lane crossover", c: "roadworks" },
  { id: 144, img: "/signs/144.png", name: "Pedestrians cross to left", c: "roadworks" },
  { id: 145, img: "/signs/145.png", name: "Pedestrians cross to right", c: "roadworks" },
  { id: 146, img: "/signs/146.png", name: "Queues likely", c: "roadworks" },
  { id: 147, img: "/signs/147.png", name: "Roadworks ahead", c: "roadworks" },
  { id: 148, img: "/signs/148.png", name: "Side road on left", c: "roadworks" },
  { id: 149, img: "/signs/149.png", name: "Side road on right", c: "roadworks" },
  { id: 150, img: "/signs/150.png", name: "Single lane", c: "roadworks" },
  { id: 151, img: "/signs/151.png", name: "Site access on left", c: "roadworks" },
  { id: 152, img: "/signs/152.png", name: "Site access on right", c: "roadworks" },
  { id: 153, img: "/signs/153.png", name: "Temporary traffic signals ahead", c: "roadworks" },
  { id: 154, img: "/signs/154.png", name: "Two nearside lanes of three closed", c: "roadworks" },
  { id: 155, img: "/signs/155.png", name: "Two Offside Lanes (Of Four) Closed", c: "roadworks" },
  { id: 156, img: "/signs/156.png", name: "Two offside lanes of three closed", c: "roadworks" },
  { id: 157, img: "/signs/157.png", name: "Two-lanes crossover", c: "roadworks" },
  { id: 158, img: "/signs/158.png", name: "Uneven surface", c: "roadworks" },
  { id: 159, img: "/signs/159.png", name: "Continuous white lines ahead.", c: "markings" },
  { id: 160, img: "/signs/160.png", name: "Drivers may not cross the lines to overtake.", c: "markings" },
  { id: 161, img: "/signs/161.png", name: "Drivers must keep left of the continuous white line.", c: "markings" },
  { id: 162, img: "/signs/162.png", name: "Drivers must not cross the broken white lines unless it is safe to do so.", c: "markings" },
  { id: 163, img: "/signs/163.png", name: "Parking Prohibited", c: "markings" },
  { id: 164, img: "/signs/164.png", name: "Parking Prohibited At Times Displayed", c: "markings" },
  { id: 165, img: "/signs/165.png", name: "The edge of the carriageway or hard shoulder.", c: "markings" },
  { id: 166, img: "/signs/166.png", name: "Traffic must not enter unless they can clear the box junction without stopping, or when turning right.", c: "markings" },
  { id: 167, img: "/signs/167.png", name: "Zebra Crossing", c: "markings" },
  { id: 168, img: "/signs/168.png", name: "100m to next exit", c: "info" },
  { id: 169, img: "/signs/169.png", name: "200m to next exit", c: "info" },
  { id: 170, img: "/signs/170.png", name: "300m Til The Next Exit", c: "info" },
  { id: 171, img: "/signs/171.png", name: "300m to next exit", c: "info" },
  { id: 172, img: "/signs/172.png", name: "Airport symbol", c: "info" },
  { id: 173, img: "/signs/173.png", name: "Alternative route for high vehicles", c: "info" },
  { id: 174, img: "/signs/174.png", name: "Cautionary speed", c: "info" },
  { id: 175, img: "/signs/175.png", name: "Contra-flow bus lane", c: "info" },
  { id: 176, img: "/signs/176.png", name: "Cul-de-sac", c: "info" },
  { id: 177, img: "/signs/177.png", name: "Direction and distance", c: "info" },
  { id: 178, img: "/signs/178.png", name: "Direction plate", c: "info" },
  { id: 179, img: "/signs/179.png", name: "Disabled persons parking bay", c: "info" },
  { id: 180, img: "/signs/180.png", name: "Distance plate", c: "info" },
  { id: 181, img: "/signs/181.png", name: "End of cycle track", c: "info" },
  { id: 182, img: "/signs/182.png", name: "End of motorway", c: "info" },
  { id: 183, img: "/signs/183.png", name: "Entry to motorway", c: "info" },
  { id: 184, img: "/signs/184.png", name: "Hard shoulder closed", c: "info" },
  { id: 185, img: "/signs/185.png", name: "Hospital 100m Ahead", c: "info" },
  { id: 186, img: "/signs/186.png", name: "Hospital ahead", c: "info" },
  { id: 187, img: "/signs/187.png", name: "In a tunnel goods vehicles cannot use right-hand lane", c: "info" },
  { id: 188, img: "/signs/188.png", name: "Lay-by ahead", c: "info" },
  { id: 189, img: "/signs/189.png", name: "Motorway ends 1km ahead", c: "info" },
  { id: 190, img: "/signs/190.png", name: "Motorway Ends 500m Ahead", c: "info" },
  { id: 191, img: "/signs/191.png", name: "Slow lane", c: "info" },
  { id: 192, img: "/signs/192.png", name: "Speed limit ahead", c: "info" },
  { id: 193, img: "/signs/193.png", name: "Start of cycle track", c: "info" },
  { id: 194, img: "/signs/194.png", name: "Supplementary plate", c: "info" },
  { id: 195, img: "/signs/195.png", name: "Tram lane on left", c: "info" },
  { id: 196, img: "/signs/196.png", name: "Tram lane on right", c: "info" },
  { id: 197, img: "/signs/197.png", name: "Unfinished road surface", c: "info" },
  { id: 198, img: "/signs/198.png", name: "With-flow bus lane on left", c: "info" },
  { id: 199, img: "/signs/199.png", name: "With-flow bus lane on right", c: "info" },
];

export const ROAD_SIGNS = RAW.map((s, i) => ({ ...s, catIndex: i + 1 }));
export default ROAD_SIGNS;
