// Road-sign flashcards — image on the front, name + meaning on the back.
// Images live in  public/signs/  and are served as  /signs/<file>.png
//
// To fix a label: find its `img` filename, cross-reference it in
// VERIFY-signs.html, and edit the `name` / `meaning` text below.

export const ROAD_SIGN_CATEGORIES = [
  { id: "regulatory", label: "Regulatory Signs",   swatch: "bg-red-600" },
  { id: "warning",    label: "Warning Signs",      swatch: "bg-amber-500", dark: true },
  { id: "roadworks",  label: "Roadworks Signs",    swatch: "bg-orange-600" },
  { id: "motorway",   label: "Motorway & Info",    swatch: "bg-blue-600" },
];

export const ROAD_SIGN_CAT = Object.fromEntries(
  ROAD_SIGN_CATEGORIES.map(c => [c.id, c])
);

const RAW = [
  { id: 1, img: "/signs/p233_00.png", name: "Stop", meaning: "Stop completely before the junction, even if the road looks clear.", c: "regulatory" },
  { id: 2, img: "/signs/p233_01.png", name: "Yield", meaning: "Give way to traffic on the road ahead; don't proceed until it's safe.", c: "regulatory" },
  { id: 3, img: "/signs/p233_02.png", name: "Yield (G\u00e9ill Sl\u00ed)", meaning: "Irish-language version of the Yield sign \u2014 same meaning.", c: "regulatory" },
  { id: 4, img: "/signs/p233_03.png", name: "School warden's stop sign", meaning: "Stop and stay stopped until children have crossed and the warden is back on the footpath.", c: "regulatory" },
  { id: 5, img: "/signs/p233_04.png", name: "No left turn", meaning: "Turning left here is prohibited.", c: "regulatory" },
  { id: 6, img: "/signs/p233_05.png", name: "No entry / no straight ahead", meaning: "You may not continue straight ahead here.", c: "regulatory" },
  { id: 7, img: "/signs/p233_06.png", name: "No right turn", meaning: "Turning right here is prohibited.", c: "regulatory" },
  { id: 8, img: "/signs/p233_07.png", name: "Parking prohibited", meaning: "No parking at this location.", c: "regulatory" },
  { id: 9, img: "/signs/p233_08.png", name: "Clearway", meaning: "No stopping or parking during the times shown on the accompanying plate.", c: "regulatory" },
  { id: 10, img: "/signs/p233_09.png", name: "Maximum speed limit 20km/h", meaning: "Do not exceed 20km/h.", c: "regulatory" },
  { id: 11, img: "/signs/p233_10.png", name: "Maximum speed limit 30km/h", meaning: "Do not exceed 30km/h \u2014 common in housing estates and slow zones.", c: "regulatory" },
  { id: 12, img: "/signs/p233_11.png", name: "Maximum speed limit 40km/h", meaning: "Do not exceed 40km/h.", c: "regulatory" },
  { id: 13, img: "/signs/p233_12.png", name: "Maximum speed limit 50km/h", meaning: "Do not exceed 50km/h \u2014 the default limit in built-up areas.", c: "regulatory" },
  { id: 14, img: "/signs/p233_13.png", name: "Maximum speed limit 60km/h", meaning: "Do not exceed 60km/h \u2014 the default limit on local roads.", c: "regulatory" },
  { id: 15, img: "/signs/p233_14.png", name: "Maximum speed limit 80km/h", meaning: "Do not exceed 80km/h \u2014 the default limit on regional roads.", c: "regulatory" },
  { id: 16, img: "/signs/p233_15.png", name: "Maximum speed limit 100km/h", meaning: "Do not exceed 100km/h \u2014 the default limit on national roads.", c: "regulatory" },
  { id: 17, img: "/signs/p233_16.png", name: "Maximum speed limit 120km/h", meaning: "Do not exceed 120km/h \u2014 the default motorway limit.", c: "regulatory" },
  { id: 18, img: "/signs/p234_01.png", name: "Maximum speed limit 60km/h (alternative design)", meaning: "Alternative 60km/h sign used on local roads.", c: "regulatory" },
  { id: 19, img: "/signs/p234_02.png", name: "Shared space", meaning: "Low-speed area where pedestrians, cyclists and vehicles mix \u2014 drive very slowly.", c: "regulatory" },
  { id: 20, img: "/signs/p234_03.png", name: "Speed limits per lane", meaning: "Different speed limits apply to different lanes.", c: "regulatory" },
  { id: 21, img: "/signs/p234_04.png", name: "No bicycles", meaning: "Cyclists may not use this road.", c: "regulatory" },
  { id: 22, img: "/signs/p234_05.png", name: "No ridden or accompanied horses", meaning: "Horses are prohibited here.", c: "regulatory" },
  { id: 23, img: "/signs/p234_06.png", name: "No entry to vehicles", meaning: "Vehicles may not enter.", c: "regulatory" },
  { id: 24, img: "/signs/p234_07.png", name: "Maximum gross weight (traffic management)", meaning: "Vehicles above the stated gross weight may not proceed.", c: "regulatory" },
  { id: 25, img: "/signs/p234_08.png", name: "Maximum vehicle length", meaning: "Vehicles longer than the stated length may not proceed.", c: "regulatory" },
  { id: 26, img: "/signs/p234_09.png", name: "Maximum vehicle width", meaning: "Vehicles wider than the stated width may not proceed.", c: "regulatory" },
  { id: 27, img: "/signs/p234_10.png", name: "Maximum axle weight", meaning: "Vehicles above the stated axle weight may not proceed.", c: "regulatory" },
  { id: 28, img: "/signs/p234_11.png", name: "No overtaking for three-axle vehicles", meaning: "Three-axle vehicles must not overtake here.", c: "regulatory" },
  { id: 29, img: "/signs/p234_12.png", name: "No horse carriages", meaning: "Horse-drawn carriages are prohibited.", c: "regulatory" },
  { id: 30, img: "/signs/p234_13.png", name: "Height restriction", meaning: "Vehicles taller than the stated height may not proceed.", c: "regulatory" },
  { id: 31, img: "/signs/p235_00.png", name: "Taxi rank", meaning: "Reserved for taxis \u2014 other vehicles must not park here.", c: "regulatory" },
  { id: 32, img: "/signs/p235_01.png", name: "No entry for large vehicles (by weight)", meaning: "Vehicles over the stated weight may not enter.", c: "regulatory" },
  { id: 33, img: "/signs/p235_02.png", name: "No U-turn", meaning: "U-turns are prohibited here.", c: "regulatory" },
  { id: 34, img: "/signs/p235_03.png", name: "No overtaking", meaning: "Overtaking is prohibited on this stretch.", c: "regulatory" },
  { id: 35, img: "/signs/p235_04.png", name: "Height restriction", meaning: "Vehicles taller than the stated height may not proceed.", c: "regulatory" },
  { id: 36, img: "/signs/p235_05.png", name: "No pedal cycles or electric scooters", meaning: "Bicycles and e-scooters may not use this road.", c: "regulatory" },
  { id: 37, img: "/signs/p235_06.png", name: "Pedestrianised street", meaning: "Closed to traffic during the hours shown \u2014 pedestrians only.", c: "regulatory" },
  { id: 38, img: "/signs/p235_07.png", name: "Parking permitted", meaning: "Parking is allowed here.", c: "regulatory" },
  { id: 39, img: "/signs/p235_08.png", name: "Disc parking plate", meaning: "Disc parking applies \u2014 display a valid parking disc.", c: "regulatory" },
  { id: 40, img: "/signs/p235_09.png", name: "Zonal restriction \u2013 no parking of large vehicles", meaning: "Large vehicles may not park anywhere in this zone.", c: "regulatory" },
  { id: 41, img: "/signs/p235_10.png", name: "End of the restriction zone", meaning: "The zonal restriction ends here.", c: "regulatory" },
  { id: 42, img: "/signs/p235_11.png", name: "Turn left ahead", meaning: "You must turn left at the junction ahead.", c: "regulatory" },
  { id: 43, img: "/signs/p235_12.png", name: "Turn right ahead", meaning: "You must turn right at the junction ahead.", c: "regulatory" },
  { id: 44, img: "/signs/p235_13.png", name: "Turn left", meaning: "You must turn left here.", c: "regulatory" },
  { id: 45, img: "/signs/p235_14.png", name: "Turn right", meaning: "You must turn right here.", c: "regulatory" },
  { id: 46, img: "/signs/p235_15.png", name: "Straight ahead", meaning: "You must continue straight ahead.", c: "regulatory" },
  { id: 47, img: "/signs/p235_16.png", name: "Keep left", meaning: "Pass to the left of the obstruction or island.", c: "regulatory" },
  { id: 48, img: "/signs/p235_17.png", name: "Keep right", meaning: "Pass to the right of the obstruction or island.", c: "regulatory" },
  { id: 49, img: "/signs/p235_18.png", name: "Pass either side", meaning: "You may pass on either side of the island.", c: "regulatory" },
  { id: 50, img: "/signs/p235_19.png", name: "Mini roundabout", meaning: "A mini-roundabout ahead \u2014 give way to traffic from the right.", c: "regulatory" },
  { id: 51, img: "/signs/p237_00.png", name: "Turn back", meaning: "You must turn back \u2014 do not continue.", c: "regulatory" },
  { id: 52, img: "/signs/p237_01.png", name: "Pedestrians, pedal cycles and electric scooters only", meaning: "Reserved for pedestrians, cyclists and e-scooters.", c: "regulatory" },
  { id: 53, img: "/signs/p237_02.png", name: "Separate bicycle and pedestrian lanes", meaning: "Cyclists and pedestrians have their own separate lanes.", c: "regulatory" },
  { id: 54, img: "/signs/p237_03.png", name: "Contra-flow cycle track", meaning: "Cyclists travel against the general direction of traffic here.", c: "regulatory" },
  { id: 55, img: "/signs/p237_04.png", name: "Go (lane open)", meaning: "Green downward arrow \u2014 this lane is open, you may proceed.", c: "regulatory" },
  { id: 56, img: "/signs/p237_05.png", name: "Stop (lane closed)", meaning: "Red X \u2014 this lane is closed; treat it like a Stop sign.", c: "regulatory" },
  { id: 57, img: "/signs/p237_06.png", name: "Move into the left-hand lane", meaning: "Merge into the left-hand lane.", c: "regulatory" },
  { id: 58, img: "/signs/p237_07.png", name: "Move into the right-hand lane", meaning: "Merge into the right-hand lane.", c: "regulatory" },
  { id: 59, img: "/signs/p237_08.png", name: "Overhead variable message sign (VMS)", meaning: "Electronic overhead sign showing live traffic information.", c: "regulatory" },
  { id: 60, img: "/signs/p237_09.png", name: "Mobile VMS displaying a text message", meaning: "Portable electronic sign showing a text warning.", c: "regulatory" },
  { id: 61, img: "/signs/p237_10.png", name: "Mobile VMS displaying chevrons", meaning: "Portable electronic sign directing you around a hazard.", c: "regulatory" },
  { id: 62, img: "/signs/p237_11.png", name: "VMS chevron format examples", meaning: "Examples of chevron patterns used on variable message signs.", c: "regulatory" },
  { id: 63, img: "/signs/p238_00.png", name: "Dangerous corner ahead", meaning: "A sharp corner is coming up \u2014 slow down.", c: "warning" },
  { id: 64, img: "/signs/p238_01.png", name: "Roundabout ahead", meaning: "A roundabout is coming up.", c: "warning" },
  { id: 65, img: "/signs/p238_02.png", name: "Mini-roundabout ahead", meaning: "A mini-roundabout is coming up.", c: "warning" },
  { id: 66, img: "/signs/p238_03.png", name: "Merging traffic", meaning: "Traffic merges from a side road ahead.", c: "warning" },
  { id: 67, img: "/signs/p238_04.png", name: "Two-way traffic", meaning: "The road ahead carries traffic in both directions.", c: "warning" },
  { id: 68, img: "/signs/p238_05.png", name: "Dangerous bend ahead", meaning: "A sharp bend is coming up \u2014 slow down.", c: "warning" },
  { id: 69, img: "/signs/p238_06.png", name: "Series of dangerous bends ahead", meaning: "Several sharp bends ahead.", c: "warning" },
  { id: 70, img: "/signs/p238_07.png", name: "Series of dangerous corners ahead", meaning: "Several sharp corners ahead.", c: "warning" },
  { id: 71, img: "/signs/p238_08.png", name: "Restricted headroom", meaning: "Limited overhead clearance ahead.", c: "warning" },
  { id: 72, img: "/signs/p238_09.png", name: "T-junction", meaning: "A T-junction is coming up.", c: "warning" },
  { id: 73, img: "/signs/p238_10.png", name: "T-junction with a road of less importance", meaning: "T-junction ahead; the side road is minor.", c: "warning" },
  { id: 74, img: "/signs/p238_11.png", name: "Y-junction with a road of less importance", meaning: "Y-junction ahead; the side road is minor.", c: "warning" },
  { id: 75, img: "/signs/p238_12.png", name: "Side road of less importance", meaning: "A minor side road joins ahead.", c: "warning" },
  { id: 76, img: "/signs/p238_13.png", name: "Crossroads with roads of less importance", meaning: "Crossroads ahead; the crossing roads are minor.", c: "warning" },
  { id: 77, img: "/signs/p238_14.png", name: "Crossroads with roads of equal importance", meaning: "Crossroads ahead \u2014 roads of equal importance.", c: "warning" },
  { id: 78, img: "/signs/p238_15.png", name: "Side road of equal importance", meaning: "A side road of equal importance joins ahead.", c: "warning" },
  { id: 79, img: "/signs/p238_16.png", name: "T-junction with a road of equal importance", meaning: "T-junction ahead with a road of equal importance.", c: "warning" },
  { id: 80, img: "/signs/p238_17.png", name: "Y-junction with a road of equal importance", meaning: "Y-junction ahead with a road of equal importance.", c: "warning" },
  { id: 81, img: "/signs/p238_18.png", name: "Staggered crossroads", meaning: "Crossroads ahead that are offset, not directly opposite.", c: "warning" },
  { id: 82, img: "/signs/p248_00.png", name: "Motorway ahead", meaning: "Blue sign warning that a motorway entrance is coming up. Learner permit holders, cyclists, pedestrians and slow vehicles must not enter.", c: "motorway" },
  { id: 83, img: "/signs/p248_01.png", name: "Motorway ahead (alternative)", meaning: "Another form of the motorway-ahead warning.", c: "motorway" },
  { id: 84, img: "/signs/p248_04.png", name: "Entry to motorway", meaning: "You are now entering the motorway \u2014 motorway rules apply from this point.", c: "motorway" },
  { id: 85, img: "/signs/p248_05.png", name: "300m to next exit", meaning: "Countdown marker: the next exit is 300 metres away.", c: "motorway" },
  { id: 86, img: "/signs/p248_06.png", name: "200m to next exit", meaning: "Countdown marker: the next exit is 200 metres away.", c: "motorway" },
  { id: 87, img: "/signs/p248_07.png", name: "100m to next exit", meaning: "Countdown marker: the next exit is 100 metres away.", c: "motorway" },
  { id: 88, img: "/signs/p248_08.png", name: "Motorway ends 1km ahead", meaning: "The motorway ends in 1km \u2014 normal road rules will resume.", c: "motorway" },
  { id: 89, img: "/signs/p248_09.png", name: "Motorway ends 500m ahead", meaning: "The motorway ends in 500 metres.", c: "motorway" },
  { id: 90, img: "/signs/p248_10.png", name: "End of motorway", meaning: "The motorway ends here; motorway rules no longer apply.", c: "motorway" },
  { id: 91, img: "/signs/p248_11.png", name: "Lane gain", meaning: "An extra lane joins the motorway ahead.", c: "motorway" },
];

export const ROAD_SIGNS = RAW.map((s, i) => ({ ...s, catIndex: i + 1 }));
export default ROAD_SIGNS;
